spring.application.name=sgroas

# Conexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sgroas_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Servidor
server.port=8080

# ===============================
# JWT
# ===============================
app.jwt.secret=SGROAS_SECRET_KEY_DE_DESARROLLO_2026_ENTREGA_1B_CON_MINIMO_32_CARACTERES
app.jwt.expiration-ms=3600000

# ===============================
# REDIS
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# REFRESH TOKEN
# ===============================
app.jwt.refresh-expiration-ms=604800000